import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { FloatingAssistant } from '@/components/assistant/FloatingAssistant';
import { AntigravityBackground } from '@/components/3d/AntigravityBackground';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Agent Hub',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} overflow-y-auto relative bg-white`}>
        <AntigravityBackground />
        <div className="relative pointer-events-auto" style={{ zIndex: 2 }}>
          {children}
        </div>
        <FloatingAssistant />
      </body>
    </html>
  );
}
